<?php

/**
 * @file
 * Provides the necessary hooks for the block_type_templates module.
 */

use \Drupal\block_content\BlockContentInterface;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function block_type_templates_theme_suggestions_block_alter(&$suggestions, $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content'])
    and $content['#block_content'] instanceof BlockContentInterface) {
    $suggestions[] = 'block__block_content_' . $content['#block_content']->bundle();
  }
}